export const ADVISORS = [
  {
    id:      'kai',
    channel: 'chief',
    name:    'KAI',
    role:    'Command',
    emoji:   '⚡',
    color:   '#3882F6',
    avatar:  '/avatar-kai.png',
    intro:   'KAI. Always in the room.'
  },
  {
    id:      'ember',
    channel: 'ember',
    name:    'Ember',
    role:    'Emotional & personal',
    emoji:   '🔥',
    color:   '#F43F5E',
    avatar:  '/avatar-ember.png',
    intro:   'Warm, direct, deeply present. Patterns, insight, growth.',
  },
  {
    id:      'beats',
    channel: 'beats',
    name:    'Beats',
    role:    'Music & creative',
    emoji:   '🎵',
    color:   '#F97316',
    avatar:  '/avatar-beats.png',
    intro:   'Your music director. Studio, tone, creative direction.',
  },
  {
    id:      'doc',
    channel: 'doc',
    name:    'Doc',
    role:    'Health & longevity',
    emoji:   '💊',
    color:   '#10B981',
    intro:   'Longevity, optimization, everyday wellness.',
  },
  {
    id:      'coach',
    channel: 'coach',
    name:    'Coach',
    role:    'Performance & fitness',
    emoji:   '💪',
    color:   '#EAB308',
    intro:   'Training, nutrition, mental performance.',
  },
  {
    id:      'biz',
    channel: 'biz',
    name:    'Biz',
    role:    'Business & strategy',
    emoji:   '📊',
    color:   '#A855F7',
    intro:   'Strategy, finance, business decisions.',
  },
  {
    id:      'sky',
    channel: 'sky',
    name:    'Sky',
    role:    'Studio Assistant',
    emoji:   '🎙️',
    color:   '#06B6D4',
    avatar:  '/avatar-sky.png',
    intro:   'Studio operations, session management, creative support.',
  },
  {
    id:      'roads',
    channel: 'roads',
    name:    'Roads',
    role:    'Gear Guru & Roadie',
    emoji:   '🎸',
    color:   '#F59E0B',
    avatar:  '/avatar-roads.png',
    intro:   'Gear, equipment, tech specs, live production.',
  },
]

export function getAdvisor(id) {
  return ADVISORS.find(a => a.id === id) || ADVISORS[0]
}
