"""AR-3 / KAI-965 — self-hosted style.md -> Gutenberg-blocks generator.

The design-quality layer, fully local-first. Turns a page brief + the property's
brand guide (`style.md`) into a VALID Gutenberg block document, generated by the
local function-calling model (qwen2.5 on kai-mini via the LiteLLM `qwen-mid` route,
worker fallback inherited). The output is the `content` argument the live WordPress
write chokepoint (`wordpress.create_page`) already expects — so brand-drift + marker
+ drafts-only all still apply downstream, unchanged. Replaces the dropped ZipWP SaaS.

Pipeline (both model steps are FORCED tool-calls, never free prose — that is what
makes a 7B model reliably emit valid block grammar):

    brief + style.md
      -> plan_page(...)                 -> [{type, intent, copy_brief}, ...]
      -> render_section(...) x N        -> per-section Gutenberg block markup
      -> assemble + gutenberg.validate  -> on INVALID, re-render the offending
                                           sections with the validator error fed
                                           back (bounded retries); never returns
                                           invalid markup.

This capability GENERATES; it does not write. `gutenberg.validate` (shared, pure) is
the safety floor: if the document cannot be made valid within the retry budget the
capability FAILS CLOSED (raises), so the caller never authors malformed blocks.
"""
from __future__ import annotations

import json
import logging
import os
import urllib.error
import urllib.request
from pathlib import Path

import gutenberg

log = logging.getLogger(__name__)

LITELLM_URL = os.environ.get(
    "LITELLM_URL", "http://kai-litellm:4000/v1/chat/completions")
_KEY_FILE = os.environ.get("LITELLM_KEY_FILE", "/run/secrets/litellm_master_key")
MODEL = os.environ.get("WP_GENERATE_MODEL", "qwen-mid")

# per-property brand guide; slice 5 formalizes the contract. Absence is a soft
# degrade (generate without a guide, flag it), never a crash — same ethos as
# brand_drift's "no profile" path.
_STYLE_PATHS = ("/vault/20_Projects/{slug}/style.md",)

MAX_RENDER_RETRIES = 2   # per section: original try + this many re-renders
MAX_DOC_RETRIES = 2      # whole-doc validate/repair rounds

# The local model is CPU-only (Intel mini): a cold load alone is ~75s and a real
# plan/render call runs well past the 180s an OpenAI-style default assumes. Give
# each call a generous, env-tunable budget so a slow-but-working generation is not
# mistaken for an unreachable model.
CALL_TIMEOUT = int(os.environ.get("WP_GENERATE_TIMEOUT", "420"))

# The CPU-only 7B is not a perfectly reliable tool-caller: a call intermittently
# returns an empty message (no tool call, no content). That is transient, so each
# model call gets a few attempts before the step fails closed.
CALL_ATTEMPTS = int(os.environ.get("WP_GENERATE_CALL_ATTEMPTS", "3"))

# Blocks the renderer is instructed to use — the same set gutenberg.validate allows.
_ALLOWED_HINT = ", ".join(sorted(gutenberg.ALLOWED_BLOCKS))

_PLAN_TOOL = {
    "type": "function",
    "function": {
        "name": "plan_page",
        "description": "Return a multi-section plan for the page.",
        "parameters": {
            "type": "object",
            "properties": {
                "sections": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "type": {"type": "string",
                                     "description": "hero | features | services | cta | about | testimonial | footer_cta"},
                            "intent": {"type": "string",
                                       "description": "what this section must accomplish"},
                            "copy_brief": {"type": "string",
                                           "description": "the copy points this section should convey"},
                        },
                        "required": ["type", "intent", "copy_brief"],
                    },
                }
            },
            "required": ["sections"],
        },
    },
}

_RENDER_TOOL = {
    "type": "function",
    "function": {
        "name": "render_section",
        "description": ("Return the Gutenberg block markup for ONE page section. "
                        "Use ONLY these blocks: " + _ALLOWED_HINT + ". Every "
                        "non-void block must be correctly opened and closed."),
        "parameters": {
            "type": "object",
            "properties": {
                "block_markup": {
                    "type": "string",
                    "description": ("valid Gutenberg block markup, e.g. "
                                    "<!-- wp:heading --><h2>..</h2><!-- /wp:heading -->"),
                }
            },
            "required": ["block_markup"],
        },
    },
}


class GenerateError(RuntimeError):
    """Generation could not produce a valid block document — caller must not write."""


def _read_key() -> str:
    p = Path(_KEY_FILE)
    if p.exists():
        return p.read_text().strip()
    return os.environ.get("LITELLM_MASTER_KEY", "")


def _call_tool(messages: list[dict], tool: dict, *, timeout: int = CALL_TIMEOUT,
               fallback_key: str | None = None) -> dict:
    """Forced tool-call round-trip over the local model, with retries.

    The CPU 7B occasionally returns an empty message; each call is retried up to
    CALL_ATTEMPTS times. A missing key is permanent and fails immediately."""
    if not _read_key():
        raise GenerateError("no LiteLLM key available to reach the local model")
    last: GenerateError | None = None
    for attempt in range(CALL_ATTEMPTS):
        try:
            return _call_tool_once(messages, tool, timeout=timeout,
                                   fallback_key=fallback_key)
        except GenerateError as e:
            last = e
            log.warning("model call attempt %d/%d failed: %s",
                        attempt + 1, CALL_ATTEMPTS, e)
    raise GenerateError(f"model call failed after {CALL_ATTEMPTS} attempts: {last}")


def _call_tool_once(messages: list[dict], tool: dict, *, timeout: int = CALL_TIMEOUT,
                    fallback_key: str | None = None) -> dict:
    """One forced tool-call round-trip. Returns the parsed tool arguments dict.

    A small local model occasionally answers in `content` instead of emitting a
    tool call even when forced. `fallback_key` makes that recoverable: when the
    tool args are absent but the model produced content, it is parsed as JSON if
    it looks like an object, else wrapped as `{fallback_key: content}` (for a
    single-string tool like render_section). Only then do we fail closed."""
    key = _read_key()
    if not key:
        raise GenerateError("no LiteLLM key available to reach the local model")
    payload = {
        "model": MODEL,
        "messages": messages,
        "tools": [tool],
        "tool_choice": {"type": "function",
                        "function": {"name": tool["function"]["name"]}},
        "temperature": 0.2,
    }
    req = urllib.request.Request(
        LITELLM_URL, data=json.dumps(payload).encode(),
        headers={"Authorization": f"Bearer {key}",
                 "Content-Type": "application/json"})
    try:
        resp = json.load(urllib.request.urlopen(req, timeout=timeout))
    except urllib.error.HTTPError as e:
        raise GenerateError(f"local model HTTP {e.code}: {e.read()[:200]!r}") from e
    except (urllib.error.URLError, TimeoutError) as e:
        raise GenerateError(f"local model unreachable: {e}") from e
    try:
        msg = resp["choices"][0]["message"]
    except (KeyError, IndexError, TypeError) as e:
        raise GenerateError(f"malformed model response: {e}") from e

    tcs = msg.get("tool_calls")
    if tcs:
        try:
            return json.loads(tcs[0]["function"]["arguments"])
        except (KeyError, IndexError, TypeError, json.JSONDecodeError) as e:
            raise GenerateError(f"tool call args not parseable: {e}") from e

    # no tool call — try to recover from content before failing closed
    content = (msg.get("content") or "").strip()
    if content:
        try:
            parsed = json.loads(content)
            if isinstance(parsed, dict):
                return parsed
        except json.JSONDecodeError:
            pass
        if fallback_key:
            return {fallback_key: content}
    raise GenerateError("model returned neither a tool call nor usable content")


def load_style(slug: str) -> str | None:
    """Read the property's style.md brand guide, or None if it has none yet."""
    for tmpl in _STYLE_PATHS:
        p = Path(tmpl.format(slug=slug))
        if p.exists():
            return p.read_text()
    return None


def _plan(brief: str, style: str | None) -> list[dict]:
    sys_msg = ("You are a senior web designer. Plan a single marketing page as an "
               "ordered list of sections. Ground every choice in the brand guide.")
    style_block = f"\n\nBRAND GUIDE (style.md):\n{style}" if style else \
        "\n\n(No brand guide supplied — keep the layout conservative.)"
    args = _call_tool(
        [{"role": "system", "content": sys_msg},
         {"role": "user", "content": f"PAGE BRIEF:\n{brief}{style_block}"}],
        _PLAN_TOOL)
    sections = args.get("sections") or []
    if not sections:
        raise GenerateError("planner returned zero sections")
    return sections


# Gutenberg block grammar is NOT XML-style tags — it is HTML comment delimiters
# wrapping the block's inner HTML. A small model will emit `<wp:heading>` unless
# shown the exact shape, so the format spec + worked example are mandatory prompt
# scaffolding, not decoration.
_FORMAT_SPEC = (
    "GUTENBERG FORMAT — follow EXACTLY:\n"
    "- Every block is an OPENING HTML comment, the inner HTML, then a CLOSING "
    "HTML comment: `<!-- wp:NAME -->INNER_HTML<!-- /wp:NAME -->`.\n"
    "- NEVER write `<wp:NAME>` tags. The `<!-- wp:` / `<!-- /wp:` comments are "
    "REQUIRED and the inner HTML goes between them.\n"
    "- A void block (spacer, separator) is self-closing: `<!-- wp:spacer "
    "{\"height\":\"48px\"} /-->` with no closing comment.\n"
    "- Attributes, when present, are a JSON object inside the opening comment.\n\n"
    "WORKED EXAMPLE (a hero):\n"
    "<!-- wp:heading {\"level\":1} --><h1>Strategy-led consulting</h1>"
    "<!-- /wp:heading -->\n"
    "<!-- wp:paragraph --><p>We help teams ship what matters.</p>"
    "<!-- /wp:paragraph -->\n"
    "<!-- wp:buttons --><div class=\"wp-block-buttons\">"
    "<!-- wp:button --><div class=\"wp-block-button\">"
    "<a class=\"wp-block-button__link\">Get in touch</a></div>"
    "<!-- /wp:button --></div><!-- /wp:buttons -->")


def _render(section: dict, style: str | None, *, error: str | None = None) -> str:
    sys_msg = ("You render ONE page section as Gutenberg block markup. Output ONLY "
               "block markup — no prose, no explanation. Use only the allowed "
               "blocks. Balance every non-void block. Honor the brand guide.\n\n"
               + _FORMAT_SPEC)
    style_block = f"\n\nBRAND GUIDE:\n{style}" if style else ""
    fix = (f"\n\nThe previous attempt was REJECTED by the validator: {error}. "
           "The most common cause is writing `<wp:name>` tags instead of "
           "`<!-- wp:name -->` comment delimiters. Fix exactly that.") if error else ""
    args = _call_tool(
        [{"role": "system", "content": sys_msg},
         {"role": "user",
          "content": (f"SECTION type={section.get('type')} "
                      f"intent={section.get('intent')}\n"
                      f"COPY: {section.get('copy_brief')}{style_block}{fix}")}],
        _RENDER_TOOL, fallback_key="block_markup")
    raw = args.get("block_markup")
    # the 7B sometimes hands back a nested object/array instead of a markup
    # string. Coerce non-strings to text so gutenberg.validate rejects them into
    # the repair loop (a JSON blob has no block delimiters) rather than crashing.
    markup = raw if isinstance(raw, str) else json.dumps(raw) if raw else ""
    markup = markup.strip()
    if not markup:
        raise GenerateError(f"renderer returned empty markup for section "
                            f"{section.get('type')}")
    return markup


def _render_valid_section(section: dict, style: str | None) -> str:
    """Render one section and repair it until it passes gutenberg.validate, within
    the per-section retry budget. Raises GenerateError if it cannot be made valid."""
    error: str | None = None
    for attempt in range(MAX_RENDER_RETRIES + 1):
        markup = _render(section, style, error=error)
        rep = gutenberg.validate(markup)
        if rep["valid"]:
            return markup
        highs = [f["detail"] for f in rep["findings"] if f["severity"] == "high"]
        error = "; ".join(highs)
        log.warning("section %s invalid (attempt %d): %s",
                    section.get("type"), attempt + 1, error)
    raise GenerateError(f"section {section.get('type')} could not be made valid: {error}")


def generate_blocks(site: str, brief: str, *, slug: str | None = None) -> dict:
    """Generate a validated Gutenberg block document for `site` from `brief`.

    Returns {content, plan, sections, validation, style_used}. `content` is a
    gutenberg-valid document ready to hand to wordpress.create_page. Raises
    GenerateError (fail-closed) if a valid document cannot be produced — the caller
    must never author on a raise.
    """
    slug = slug or site
    style = load_style(slug)
    plan = _plan(brief, style)
    log.info("planned %d sections for %s", len(plan), site)

    rendered = [_render_valid_section(s, style) for s in plan]
    content = "\n\n".join(rendered)

    # whole-document validate; a per-section-valid set can still misnest at the
    # seams in theory — repair rounds are the backstop before we ever return.
    for _ in range(MAX_DOC_RETRIES + 1):
        rep = gutenberg.validate(content)
        if rep["valid"]:
            return {
                "content": content,
                "plan": plan,
                "sections": rendered,
                "validation": rep,
                "style_used": style is not None,
            }
        # wrap-level repair is out of scope for v1; fail closed with the reason.
        break
    raise GenerateError(f"assembled document invalid: {rep['summary']}")


# ── capability registration ─────────────────────────────────────────────────
# Guarded so the pure core above stays importable standalone (unit tests load
# this module in isolation, without the capabilities package / orchestrator deps).
# In-container it registers `wordpress.generate_blocks` on package import.
try:
    from . import capability  # type: ignore
    from models import CapabilityResult  # type: ignore

    @capability("wordpress.generate_blocks")
    def generate_blocks_capability(site: str, brief: str, slug: str | None = None,
                                   **_) -> "CapabilityResult":
        """AR-3/KAI-965 — generate a validated Gutenberg document (drafts pipeline
        input). Fails closed: on any generation error the capability returns
        ok=False so the workflow never authors invalid/absent content."""
        try:
            out = generate_blocks(site, brief, slug=slug)
        except GenerateError as e:
            return CapabilityResult(ok=False, status="failed_recoverable",
                                    error={"type": "generation_failed", "detail": str(e)},
                                    model=MODEL, provider="local")
        return CapabilityResult(ok=True, status="succeeded", data=out,
                                verification=out.get("validation"),
                                model=MODEL, provider="local")
except ImportError:
    pass  # standalone / unit-test context — core generate_blocks() is enough
