"""
S6-3 Proposal generator — reads pattern JSON from S6-2, generates structured
Markdown proposals for patterns with evidence_count >= 2, posts a summary via the
notify gateway, writes proposals to vault/60_Council/learning/.

Human-in-the-loop: system proposes, Leo merges — NO auto-apply.
"""

import datetime
import json
import logging
import pathlib


log = logging.getLogger(__name__)

_VAULT_LEARNING = pathlib.Path("/vault/60_Council/learning")

_EVIDENCE_THRESHOLD = 2  # only generate proposals for patterns with this many+ evidence items


# ── Alert helper ──────────────────────────────────────────────────────────────

def _post_alert(text: str) -> bool:
    """Route the learning-loop summary through the notify gateway (single voice)."""
    try:
        from tg_alert import tg_alert
        return tg_alert(text)
    except Exception as exc:
        log.warning("proposal-gen alert exception: %s", exc)
        return False


# ── Proposal rendering ────────────────────────────────────────────────────────

_CAUSE_MAP = {
    "broken_tool":       "Tool or dependency missing/misconfigured",
    "transport_failure": "Transport layer (SSH/HTTP) unreliable or misconfigured",
    "wrong_gate":        "Approval gate triggered unnecessarily or too frequently",
    "workflow_logic":    "Workflow verification or logic error",
}

_ACTION_MAP = {
    "broken_tool":       "Audit capability registration and binary paths; add health-check probe",
    "transport_failure": "Verify SSH key, purge endpoint URL, and retry/backoff parameters",
    "wrong_gate":        "Review autonomy policy for this step; consider tightening gate trigger conditions",
    "workflow_logic":    "Review step verification logic; add expected-output contract test",
}


def _render_proposal(p: dict, week: str) -> str:
    ptype       = p["pattern_type"]
    cap         = p["capability"]
    err_sig     = p["error_signature"] or "(no specific signature)"
    ev_count    = p["evidence_count"]
    evidence    = p["evidence"][:5]

    ev_lines = []
    for i, e in enumerate(evidence, 1):
        parts = [f"{k}: {v}" for k, v in e.items() if v is not None]
        ev_lines.append(f"  {i}. {', '.join(parts)}")
    ev_block = "\n".join(ev_lines) or "  (none recorded)"

    return f"""# Proposal — {ptype.upper().replace('_', ' ')}: {cap}

**Week:** {week}
**Pattern type:** `{ptype}`
**Capability:** `{cap}`
**Error signature:** `{err_sig}`
**Evidence count:** {ev_count}

## Root cause

{_CAUSE_MAP.get(ptype, "Unknown pattern type")}

## Evidence sample

{ev_block}

## Proposed action

{_ACTION_MAP.get(ptype, "Review and address the underlying issue")}

## Proposed code diff

```
# TODO: Implement fix for {cap}
# Root cause: {err_sig}
# Evidence count: {ev_count}
```

## Status

- [ ] Reviewed by Leo
- [ ] Fix implemented
- [ ] Verified in production

---
*Generated by S6-3 proposal generator — {datetime.datetime.utcnow().isoformat()}Z*
*Human-in-the-loop: system proposes, Leo merges, no auto-apply.*
"""


# ── Core: generate proposals from a pattern file ──────────────────────────────

def generate_proposals(pattern_file: pathlib.Path | None = None) -> dict:
    """
    Read pattern JSON (defaults to latest in vault/60_Council/learning/),
    generate Markdown proposals for qualifying patterns,
    post an alert summary, return summary dict.
    """
    if pattern_file is None:
        candidates = sorted(_VAULT_LEARNING.glob("*-patterns.json"))
        if not candidates:
            return {"ok": False, "error": "No pattern files found"}
        pattern_file = candidates[-1]

    data = json.loads(pattern_file.read_text())
    week     = data["week"]
    patterns = data["patterns"]

    qualifying = [p for p in patterns if p["evidence_count"] >= _EVIDENCE_THRESHOLD]
    proposals_written = []

    for p in qualifying:
        slug      = f"{p['capability'].replace('.', '-').replace('/', '-')}_{p['pattern_type']}"
        out_path  = _VAULT_LEARNING / f"{week}-proposal-{slug}.md"
        md        = _render_proposal(p, week)
        out_path.write_text(md)
        proposals_written.append(str(out_path))
        log.info("proposal-gen: wrote %s", out_path.name)

    # Alert summary
    if proposals_written:
        lines = [f"*KAI Learning Loop — {week}*"]
        lines.append(f"Pattern aggregation found *{len(patterns)} patterns*, *{len(qualifying)} actionable* (evidence ≥ {_EVIDENCE_THRESHOLD}):")
        for p in qualifying:
            lines.append(f"  • `{p['capability']}` [{p['pattern_type']}] — {p['evidence_count']} evidence items")
        lines.append(f"\n{len(proposals_written)} proposal(s) written to vault/60_Council/learning/")
        lines.append("_Human-in-the-loop: system proposes, Leo merges._")
        alert_text = "\n".join(lines)
        alert_posted = _post_alert(alert_text)
    else:
        alert_text = f"KAI Learning Loop — {week}: {len(patterns)} patterns, none qualify (all below threshold {_EVIDENCE_THRESHOLD})"
        alert_posted = _post_alert(alert_text)

    return {
        "ok": True,
        "week": week,
        "pattern_file": str(pattern_file),
        "total_patterns": len(patterns),
        "qualifying_patterns": len(qualifying),
        "proposals_written": proposals_written,
        "alert_posted": alert_posted,
    }
